# 07. 원근 변환

In [2]:
import cv2
import numpy as np

card = "./images/card.jpg"

In [5]:
img = cv2.imread(card)

width, height = 600, 350

# 변형할 지점 선택 : 시계방항
src = np.array(
    [[[54, 261], [981, 128], [1213, 560], [194, 735]]], dtype=np.float32)

# 결과물 출력할 형태 : 시계방향
dst = np.array([[0, 0], [width, 0], [width, height],
                [0, height]], dtype=np.float32)

# 원근을 변형하기 위한 matrix 생성
mat = cv2.getPerspectiveTransform(src, dst)
print(mat)

# img를 mat에 의해 변환
result = cv2.warpPerspective(img, mat, (width, height))

cv2.imshow("card img", img)
cv2.imshow("result", result)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 6.28270120e-01 -1.85565014e-01  1.45058823e+01]
 [ 1.20997970e-01  8.43346752e-01 -2.26647393e+02]
 [-2.25609902e-05  2.65181603e-04  1.00000000e+00]]
