In [1]:
import cv2
import numpy as np

In [3]:
dilate = "./images/dilate.png"
erode = "./images/erode.png"

In [5]:
img = cv2.imread(dilate)
kernel = np.ones((3, 3), dtype=np.uint8)
dilate_1 = cv2.dilate(img, kernel, iterations=1)
dilate_2 = cv2.dilate(img, kernel, iterations=2)
dilate_3 = cv2.dilate(img, kernel, iterations=3)

cv2.imshow("img", img)
cv2.imshow("dilate_1", dilate_1)
cv2.imshow("dilate_2", dilate_2)
cv2.imshow("dilate_3", dilate_3)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img = cv2.imread(erode)

kernel = np.ones((3, 3), dtype=np.uint8)
erode_1 = cv2.erode(img, kernel, iterations=1)
erode_2 = cv2.erode(img, kernel, iterations=2)
erode_3 = cv2.erode(img, kernel, iterations=3)

cv2.imshow("img", img)
cv2.imshow("erode_1", erode_1)
cv2.imshow("erode_2", erode_2)
cv2.imshow("erode_3", erode_3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread(erode)

kernel = np.ones((3, 3), dtype=np.uint8)

erode_3_1 = cv2.erode(img, kernel, iterations=3)
dilate_3_1 = cv2.dilate(erode_3_1, kernel, iterations=3)

cv2.imshow("img", img)
cv2.imshow("erode_3_1", erode_3_1)
cv2.imshow("dilate_3_1", dilate_3_1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img = cv2.imread(dilate)

kernel = np.ones((3, 3), dtype=np.uint8)

dilate_3_2 = cv2.dilate(img, kernel, iterations=3)
erode_3_2 = cv2.erode(dilate_3_2, kernel, iterations=3)

cv2.imshow("img", img)
cv2.imshow("dilate_3_2", dilate_3_2)
cv2.imshow("erode_3_2", erode_3_2)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1]
 [1 1 1]
 [1 1 1]]
