# 실습 2-2. Threshold에 적용

## 트랙바 실습한 것을 참고해서, threshold에 트랙바를 적용

In [1]:
import cv2
import numpy as numpy

book="./images/book.jpg"

In [4]:
img = cv2.imread(book, cv2.COLOR_BGR2BGRA)
original = cv2.imread(book)

name = "Trackbar"
trackbar_name = "change_blight"
cv2.namedWindow(name)
cv2.createTrackbar(trackbar_name, name, 0, 255, lambda x: x)

while True:
    blight = cv2.getTrackbarPos(trackbar_name, name)
    # binary 옵션 : cv2.THRESH_BINARY => 임계값보다 크면 흰색, 작으면 검은색
    ret, binary = cv2.threshold(img, blight, 255, cv2.THRESH_BINARY)
    # print(ret)
    # print(binary)

    cv2.imshow("img", img)
    cv2.imshow(name, binary)
    cv2.imshow("original", original)

    if cv2.waitKey(1) == ord("q"):
        break
cv2.destroyAllWindows()

In [3]:
img = cv2.imread(book, cv2.IMREAD_GRAYSCALE)
original = cv2.imread(book)

name = "Trackbar"
trackbar_name = "blight"
cv2.namedWindow(name)
cv2.createTrackbar(trackbar_name, name, 127, 255, lambda x: x)

while True:
    blight = cv2.getTrackbarPos(trackbar_name, name)
    # binary 옵션 : cv2.THRESH_BINARY => 임계값보다 크면 흰색, 작으면 검은색
    ret, binary = cv2.threshold(img, blight, 255, cv2.THRESH_BINARY)
    # print(ret)
    # print(binary)

    cv2.imshow("img", img)
    cv2.imshow(name, binary)
    cv2.imshow("original", original)

    if cv2.waitKey(1) == ord("q"):
        break
cv2.destroyAllWindows()

In [6]:
cv2.IMREAD_GRAYSCALE
cv2.COLOR_BGR2GRAY

6

In [11]:
img = cv2.imread(book, cv2.IMREAD_GRAYSCALE)

# b,g,r=cv2.split(img)
g = cv2.split(img)
print(g)

(array([[211, 211, 211, ..., 190, 190, 190],
       [208, 208, 208, ..., 191, 191, 190],
       [205, 205, 205, ..., 191, 191, 191],
       ...,
       [117, 117, 117, ...,  42,  42,  42],
       [117, 117, 117, ...,  42,  42,  42],
       [117, 117, 117, ...,  42,  42,  42]], shape=(960, 640), dtype=uint8),)


In [9]:
img = cv2.imread(book, cv2.COLOR_BGR2GRAY)

b, g, r = cv2.split(img)

print(b, g, r)

[[215 215 215 ... 204 204 204]
 [212 212 212 ... 205 205 204]
 [210 210 210 ... 207 207 207]
 ...
 [ 37  37  37 ...  56  54  54]
 [ 35  35  37 ...  54  54  54]
 [ 35  35  37 ...  54  54  54]] [[210 210 210 ... 194 194 194]
 [207 207 207 ... 195 195 194]
 [205 205 205 ... 194 194 194]
 ...
 [115 115 115 ...  43  42  42]
 [115 115 115 ...  43  42  42]
 [115 115 115 ...  43  42  42]] [[211 211 211 ... 177 177 177]
 [208 208 208 ... 178 178 177]
 [204 204 204 ... 180 180 180]
 ...
 [152 152 152 ...  35  36  36]
 [152 152 152 ...  35  36  36]
 [152 152 152 ...  35  36  36]]
